FROM ubuntu:latest AS builder

# Update Ubuntu Software repository
RUN apt-get update && apt-get -y install \
    cmake \
    make  \
    g++ \
    libboost-dev \
    protobuf-compiler-grpc \
    libgrpc++-dev

WORKDIR /polluxapp
COPY cmake cmake
COPY src src
COPY thirdparty thirdparty
COPY CMakeLists.txt .
RUN cmake . && make -j$(nproc)

FROM pollux-qarnot:latest AS polluxapp-qarnot
RUN apt-get update && apt-get -y install libgrpc++
WORKDIR /root
COPY --from=builder /polluxapp/src/c++/polluxapp ./
EXPOSE 50000
