# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pollux.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pollux.proto',
  package='pollux',
  syntax='proto3',
  serialized_options=b'Z\023pollux/private/grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cpollux.proto\x12\x06pollux\"b\n\rPolluxVersion\x12.\n\x07version\x18\x01 \x01(\x0e\x32\x1d.pollux.PolluxVersion.Version\"!\n\x07Version\x12\t\n\x05\x44UMMY\x10\x00\x12\x0b\n\x07\x43URRENT\x10\x01\"Q\n\rPolluxMessage\x12\x0e\n\x06origin\x18\x01 \x01(\r\x12\x14\n\x0c\x64\x65stinations\x18\x02 \x03(\r\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\"%\n\x15PolluxMessageResponse\x12\x0c\n\x04info\x18\x01 \x01(\tB\x15Z\x13pollux/private/grpcb\x06proto3'
)



_POLLUXVERSION_VERSION = _descriptor.EnumDescriptor(
  name='Version',
  full_name='pollux.PolluxVersion.Version',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DUMMY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CURRENT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=89,
  serialized_end=122,
)
_sym_db.RegisterEnumDescriptor(_POLLUXVERSION_VERSION)


_POLLUXVERSION = _descriptor.Descriptor(
  name='PolluxVersion',
  full_name='pollux.PolluxVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='pollux.PolluxVersion.version', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _POLLUXVERSION_VERSION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=122,
)


_POLLUXMESSAGE = _descriptor.Descriptor(
  name='PolluxMessage',
  full_name='pollux.PolluxMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='origin', full_name='pollux.PolluxMessage.origin', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='destinations', full_name='pollux.PolluxMessage.destinations', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='pollux.PolluxMessage.key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='pollux.PolluxMessage.value', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=205,
)


_POLLUXMESSAGERESPONSE = _descriptor.Descriptor(
  name='PolluxMessageResponse',
  full_name='pollux.PolluxMessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='pollux.PolluxMessageResponse.info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=244,
)

_POLLUXVERSION.fields_by_name['version'].enum_type = _POLLUXVERSION_VERSION
_POLLUXVERSION_VERSION.containing_type = _POLLUXVERSION
DESCRIPTOR.message_types_by_name['PolluxVersion'] = _POLLUXVERSION
DESCRIPTOR.message_types_by_name['PolluxMessage'] = _POLLUXMESSAGE
DESCRIPTOR.message_types_by_name['PolluxMessageResponse'] = _POLLUXMESSAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PolluxVersion = _reflection.GeneratedProtocolMessageType('PolluxVersion', (_message.Message,), {
  'DESCRIPTOR' : _POLLUXVERSION,
  '__module__' : 'pollux_pb2'
  # @@protoc_insertion_point(class_scope:pollux.PolluxVersion)
  })
_sym_db.RegisterMessage(PolluxVersion)

PolluxMessage = _reflection.GeneratedProtocolMessageType('PolluxMessage', (_message.Message,), {
  'DESCRIPTOR' : _POLLUXMESSAGE,
  '__module__' : 'pollux_pb2'
  # @@protoc_insertion_point(class_scope:pollux.PolluxMessage)
  })
_sym_db.RegisterMessage(PolluxMessage)

PolluxMessageResponse = _reflection.GeneratedProtocolMessageType('PolluxMessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _POLLUXMESSAGERESPONSE,
  '__module__' : 'pollux_pb2'
  # @@protoc_insertion_point(class_scope:pollux.PolluxMessageResponse)
  })
_sym_db.RegisterMessage(PolluxMessageResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
