# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pollux_payload.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pollux_pb2 as pollux__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pollux_payload.proto',
  package='pollux',
  syntax='proto3',
  serialized_options=b'Z\023pollux/private/grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14pollux_payload.proto\x12\x06pollux\x1a\x0cpollux.proto\"Y\n\x13PayloadReadyMessage\x12\x0c\n\x04info\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12&\n\x07version\x18\x03 \x01(\x0b\x32\x15.pollux.PolluxVersion\"$\n\x14PayloadReadyResponse\x12\x0c\n\x04info\x18\x01 \x01(\t\"5\n\x16PayloadInactiveMessage\x12\x0c\n\x04info\x18\x01 \x01(\t\x12\r\n\x05since\x18\x02 \x01(\x04\"\'\n\x17PayloadInactiveResponse\x12\x0c\n\x04info\x18\x01 \x01(\t\"#\n\x13PayloadStartMessage\x12\x0c\n\x04info\x18\x01 \x01(\t\"$\n\x14PayloadStartResponse\x12\x0c\n\x04info\x18\x01 \x01(\t\"\'\n\x17PayloadTerminateMessage\x12\x0c\n\x04info\x18\x01 \x01(\t\"\x1a\n\x18PayloadTerminateResponse2\xf6\x01\n\rPolluxPayload\x12M\n\x13PolluxCommunication\x12\x15.pollux.PolluxMessage\x1a\x1d.pollux.PolluxMessageResponse\"\x00\x12\x44\n\x05Start\x12\x1b.pollux.PayloadStartMessage\x1a\x1c.pollux.PayloadStartResponse\"\x00\x12P\n\tTerminate\x12\x1f.pollux.PayloadTerminateMessage\x1a .pollux.PayloadTerminateResponse\"\x00\x32\x84\x02\n\x10PolluxletPayload\x12K\n\x0cPayloadReady\x12\x1b.pollux.PayloadReadyMessage\x1a\x1c.pollux.PayloadReadyResponse\"\x00\x12T\n\x0fPayloadInactive\x12\x1e.pollux.PayloadInactiveMessage\x1a\x1f.pollux.PayloadInactiveResponse\"\x00\x12M\n\x13PolluxCommunication\x12\x15.pollux.PolluxMessage\x1a\x1d.pollux.PolluxMessageResponse\"\x00\x42\x15Z\x13pollux/private/grpcb\x06proto3'
  ,
  dependencies=[pollux__pb2.DESCRIPTOR,])




_PAYLOADREADYMESSAGE = _descriptor.Descriptor(
  name='PayloadReadyMessage',
  full_name='pollux.PayloadReadyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='pollux.PayloadReadyMessage.info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='pollux.PayloadReadyMessage.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='pollux.PayloadReadyMessage.version', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=135,
)


_PAYLOADREADYRESPONSE = _descriptor.Descriptor(
  name='PayloadReadyResponse',
  full_name='pollux.PayloadReadyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='pollux.PayloadReadyResponse.info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=173,
)


_PAYLOADINACTIVEMESSAGE = _descriptor.Descriptor(
  name='PayloadInactiveMessage',
  full_name='pollux.PayloadInactiveMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='pollux.PayloadInactiveMessage.info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='since', full_name='pollux.PayloadInactiveMessage.since', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=228,
)


_PAYLOADINACTIVERESPONSE = _descriptor.Descriptor(
  name='PayloadInactiveResponse',
  full_name='pollux.PayloadInactiveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='pollux.PayloadInactiveResponse.info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=269,
)


_PAYLOADSTARTMESSAGE = _descriptor.Descriptor(
  name='PayloadStartMessage',
  full_name='pollux.PayloadStartMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='pollux.PayloadStartMessage.info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=306,
)


_PAYLOADSTARTRESPONSE = _descriptor.Descriptor(
  name='PayloadStartResponse',
  full_name='pollux.PayloadStartResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='pollux.PayloadStartResponse.info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=344,
)


_PAYLOADTERMINATEMESSAGE = _descriptor.Descriptor(
  name='PayloadTerminateMessage',
  full_name='pollux.PayloadTerminateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='pollux.PayloadTerminateMessage.info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=385,
)


_PAYLOADTERMINATERESPONSE = _descriptor.Descriptor(
  name='PayloadTerminateResponse',
  full_name='pollux.PayloadTerminateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=413,
)

_PAYLOADREADYMESSAGE.fields_by_name['version'].message_type = pollux__pb2._POLLUXVERSION
DESCRIPTOR.message_types_by_name['PayloadReadyMessage'] = _PAYLOADREADYMESSAGE
DESCRIPTOR.message_types_by_name['PayloadReadyResponse'] = _PAYLOADREADYRESPONSE
DESCRIPTOR.message_types_by_name['PayloadInactiveMessage'] = _PAYLOADINACTIVEMESSAGE
DESCRIPTOR.message_types_by_name['PayloadInactiveResponse'] = _PAYLOADINACTIVERESPONSE
DESCRIPTOR.message_types_by_name['PayloadStartMessage'] = _PAYLOADSTARTMESSAGE
DESCRIPTOR.message_types_by_name['PayloadStartResponse'] = _PAYLOADSTARTRESPONSE
DESCRIPTOR.message_types_by_name['PayloadTerminateMessage'] = _PAYLOADTERMINATEMESSAGE
DESCRIPTOR.message_types_by_name['PayloadTerminateResponse'] = _PAYLOADTERMINATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PayloadReadyMessage = _reflection.GeneratedProtocolMessageType('PayloadReadyMessage', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOADREADYMESSAGE,
  '__module__' : 'pollux_payload_pb2'
  # @@protoc_insertion_point(class_scope:pollux.PayloadReadyMessage)
  })
_sym_db.RegisterMessage(PayloadReadyMessage)

PayloadReadyResponse = _reflection.GeneratedProtocolMessageType('PayloadReadyResponse', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOADREADYRESPONSE,
  '__module__' : 'pollux_payload_pb2'
  # @@protoc_insertion_point(class_scope:pollux.PayloadReadyResponse)
  })
_sym_db.RegisterMessage(PayloadReadyResponse)

PayloadInactiveMessage = _reflection.GeneratedProtocolMessageType('PayloadInactiveMessage', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOADINACTIVEMESSAGE,
  '__module__' : 'pollux_payload_pb2'
  # @@protoc_insertion_point(class_scope:pollux.PayloadInactiveMessage)
  })
_sym_db.RegisterMessage(PayloadInactiveMessage)

PayloadInactiveResponse = _reflection.GeneratedProtocolMessageType('PayloadInactiveResponse', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOADINACTIVERESPONSE,
  '__module__' : 'pollux_payload_pb2'
  # @@protoc_insertion_point(class_scope:pollux.PayloadInactiveResponse)
  })
_sym_db.RegisterMessage(PayloadInactiveResponse)

PayloadStartMessage = _reflection.GeneratedProtocolMessageType('PayloadStartMessage', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOADSTARTMESSAGE,
  '__module__' : 'pollux_payload_pb2'
  # @@protoc_insertion_point(class_scope:pollux.PayloadStartMessage)
  })
_sym_db.RegisterMessage(PayloadStartMessage)

PayloadStartResponse = _reflection.GeneratedProtocolMessageType('PayloadStartResponse', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOADSTARTRESPONSE,
  '__module__' : 'pollux_payload_pb2'
  # @@protoc_insertion_point(class_scope:pollux.PayloadStartResponse)
  })
_sym_db.RegisterMessage(PayloadStartResponse)

PayloadTerminateMessage = _reflection.GeneratedProtocolMessageType('PayloadTerminateMessage', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOADTERMINATEMESSAGE,
  '__module__' : 'pollux_payload_pb2'
  # @@protoc_insertion_point(class_scope:pollux.PayloadTerminateMessage)
  })
_sym_db.RegisterMessage(PayloadTerminateMessage)

PayloadTerminateResponse = _reflection.GeneratedProtocolMessageType('PayloadTerminateResponse', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOADTERMINATERESPONSE,
  '__module__' : 'pollux_payload_pb2'
  # @@protoc_insertion_point(class_scope:pollux.PayloadTerminateResponse)
  })
_sym_db.RegisterMessage(PayloadTerminateResponse)


DESCRIPTOR._options = None

_POLLUXPAYLOAD = _descriptor.ServiceDescriptor(
  name='PolluxPayload',
  full_name='pollux.PolluxPayload',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=416,
  serialized_end=662,
  methods=[
  _descriptor.MethodDescriptor(
    name='PolluxCommunication',
    full_name='pollux.PolluxPayload.PolluxCommunication',
    index=0,
    containing_service=None,
    input_type=pollux__pb2._POLLUXMESSAGE,
    output_type=pollux__pb2._POLLUXMESSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Start',
    full_name='pollux.PolluxPayload.Start',
    index=1,
    containing_service=None,
    input_type=_PAYLOADSTARTMESSAGE,
    output_type=_PAYLOADSTARTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Terminate',
    full_name='pollux.PolluxPayload.Terminate',
    index=2,
    containing_service=None,
    input_type=_PAYLOADTERMINATEMESSAGE,
    output_type=_PAYLOADTERMINATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POLLUXPAYLOAD)

DESCRIPTOR.services_by_name['PolluxPayload'] = _POLLUXPAYLOAD


_POLLUXLETPAYLOAD = _descriptor.ServiceDescriptor(
  name='PolluxletPayload',
  full_name='pollux.PolluxletPayload',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=665,
  serialized_end=925,
  methods=[
  _descriptor.MethodDescriptor(
    name='PayloadReady',
    full_name='pollux.PolluxletPayload.PayloadReady',
    index=0,
    containing_service=None,
    input_type=_PAYLOADREADYMESSAGE,
    output_type=_PAYLOADREADYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PayloadInactive',
    full_name='pollux.PolluxletPayload.PayloadInactive',
    index=1,
    containing_service=None,
    input_type=_PAYLOADINACTIVEMESSAGE,
    output_type=_PAYLOADINACTIVERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PolluxCommunication',
    full_name='pollux.PolluxletPayload.PolluxCommunication',
    index=2,
    containing_service=None,
    input_type=pollux__pb2._POLLUXMESSAGE,
    output_type=pollux__pb2._POLLUXMESSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POLLUXLETPAYLOAD)

DESCRIPTOR.services_by_name['PolluxletPayload'] = _POLLUXLETPAYLOAD

# @@protoc_insertion_point(module_scope)
